apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  api_key: {{ .Values.apiKey | b64enc }}
  api_key_2: {{ .Values.apiKey2 | b64enc }}
  tidbyt_token: {{ .Values.tidbytToken | b64enc }}
